app.datasource.login.jdbc-url=jdbc:postgresql://localhost:5432/OmniKeyAUTH_db
app.datasource.login.username=postgres
app.datasource.login.password=Maxi1312$
app.datasource.login.driver-class-name=org.postgresql.Driver

app.datasource.scraper.jdbc-url=jdbc:postgresql://localhost:5432/OmniKeyGames_db
app.datasource.scraper.username=postgres
app.datasource.scraper.password=Maxi1312$
app.datasource.scraper.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.lifecycle.timeout-per-shutdown-phase=10s
spring.thymeleaf.encoding=UTF-8
spring.web.resources.chain.html-image-hash=false
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true